### ISSUE TITLE
Output console do not read user Input

### ISSUE THREAD

**Issue by matscode** [formulahendry/CodeRunnerVS#1]
While i try to ask for user input in my Kotlin code. Input is not visible as a sign it is been received nor does the return button works.
![screenshot from 2017-08-06 05-02-38](https://user-images.githubusercontent.com/8417404/29000525-91f72e2a-7a65-11e7-8175-bfaae6058bcd.png)

**Comment by formulahendry** [comment]
This repo is Code Runner for **Visual Studio** not **Visual Studio Code**. You need to go to https://github.com/formulahendry/vscode-code-runner/issues.
For the input support, you could refer to https://github.com/formulahendry/vscode-code-runner/issues/91

**Comment by matscode** [comment]
Oooh.. my bad.. i did not even take a clear look.. please excuse my ignorance...

**Comment by formulahendry** [comment]
Never mind.
